version: '3'

services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'devdeva'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: